char *_strcpy(char *dest, char *src);
void print_array(int *a, int n);
void rev_string(char *s);
void puts_half(char *str);
void puts2(char *str);
void print_rev(char *s);
void _puts(char *str);
int _putchar(char c);
int _strlen(char *s);
void reset_to_98(int *n);
void swap_int(int *a, int *b);
